### PR TITLE
Maven project setup/more lovely .gitignore and of course my vision of basic versions of request/response

### PR DESCRIPTION
**Pull request by Dmitry404**

### CODE REVIEW

**Comment by alex-dukhno** [comment]
It is all very nice, but have tests because of tests and have objects because of objects. I didn't think that we created list of objects to make them real in code.

Probably, we have to add some kind of RequestDeserializer & ResponseSerializer interfaces into the **view** and mock them up in controller. Also add some interface to **model** which produces Res from Req. What do you think?

I believe we should somehow show that Res&Req are not created from air.

PS: I don't like names **view**, **model**, **controller** too.

**Comment by Dmitry404** [comment]
This is just a view of how these classes could look like in their basic form we could start from. Instead of showing it in diagrams or text files I created them as a piece of code. Anyway, the purpose of this PL is to create a basic project's structure and to show my vision of what we are discussing in #4.  So far, let's postpone working on the boundaries till the first integration test is written. I'll log an issue for that.

**Comment by Dmitry404** [comment]
Here you are #6 

Regarding this PL, I'm going to close it and create a new one which would contain project's setup only. 

**Plz confirm.**

**Comment by alex-dukhno** [comment]
I am OK with that.

BTW you could show their structure in code snippets without creating a PR like

``` java
public interface Request {
    String body();

    String contentType();

    int contentLength();

    String queryString();

    String protocol();

    String host();

    int port();
}
```

But I don't know if it's convenient for you.

**Comment by Dmitry404** [comment]
>  code snippets

Sure, totally forgot about gists. It would work of course.

Closing this PR. New one on the way 🎱

**Pull request closed without merging**
